databases:
  - name: clinicos-db
    databaseName: clinic_db
    user: clinicos

services:
  - type: web
    name: clinicos-api
    runtime: python
    plan: starter
    rootDir: Backend_db
    buildCommand: pip install -r requirements.txt
    startCommand: >-
      gunicorn --bind 0.0.0.0:$PORT
      --workers 1
      --timeout 120
      --max-requests 500
      --max-requests-jitter 50
      "app:create_app()"

    disk:
      name: clinic-uploads
      mountPath: /var/data/clinic_uploads
      sizeGB: 10
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: clinicos-db
          property: connectionString
      - key: UPLOAD_BASE_DIR
        value: /var/data/clinic_uploads
      - key: FLASK_DEBUG
        value: false
      - key: CORS_ORIGINS
        value: https://clinicos-frontend.onrender.com
      - key: OCR_SERVICE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: TOTP_SECRET
        sync: false

  - type: web
    name: clinicos-frontend
    runtime: node
    plan: starter
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: BACKEND_URL
        value: https://clinicos-api-69mw.onrender.com
      - key: NODE_VERSION
        value: 20
